import type { GeneralExamination } from '@/types/patientClinical.types';

type GeneralExamField = Exclude<keyof GeneralExamination, 'prakriti'>;

export const GENERAL_EXAMINATION_OPTIONS: Record<GeneralExamField, readonly string[]> = {
  nadi: [
    'Vata-predominant, irregular',
    'Pitta-predominant, moderate',
    'Kapha-predominant, slow',
    'Tridosha balanced',
    'Vata',
    'Pitta',
    'Kapha',
    'Tridosha',
    'Irregular',
    'Normal',
  ],
  jivha: [
    'Pale with light coating',
    'Red / inflamed',
    'Coated / white',
    'Dry / cracked',
    'Moist / pink',
    'Vata',
    'Pitta',
    'Kapha',
    'Tridosha',
    'Normal',
  ],
  stool: [
    'Regular, tendency to dryness',
    'Regular, normal',
    'Loose / frequent',
    'Constipated',
    'Irregular',
    'Tikshna',
    'Manda',
    'Ushna',
    'Sama',
    'Hard / dry',
  ],
  urine: [
    'Clear, adequate',
    'Scanty',
    'Frequent',
    'Burning',
    'Cloudy',
    'Tikshna',
    'Manda',
    'Ushna',
    'Sama',
    'Normal',
  ],
  hunger: ['Irregular', 'Normal', 'Increased', 'Decreased', 'Variable'],
  digestion: ['Variable', 'Normal', 'Good', 'Poor', 'Slow', 'Fast'],
  sleep: [
    'Light, interrupted',
    'Normal',
    'Good',
    'Poor',
    'Deep / sound',
    'Insufficient',
    'Disturbed',
  ],
  intolerance: [
    'Cold foods',
    'Spicy foods',
    'Dairy',
    'Gluten',
    'Nuts',
    'None',
    'Multiple / other',
  ],
};
